// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PrParcial.Models;

namespace PrParcial.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191210143747_CxParcial")]
    partial class CxParcial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("PrParcial.Models.ClienteItem", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombre");

                    b.HasKey("Id_cliente");

                    b.ToTable("CLIENTEITEM");
                });

            modelBuilder.Entity("PrParcial.Models.RutaItem", b =>
                {
                    b.Property<int>("Id_ruta")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Destino");

                    b.Property<string>("Origen");

                    b.Property<int>("Valor");

                    b.HasKey("Id_ruta");

                    b.ToTable("RUTAITEM");
                });

            modelBuilder.Entity("PrParcial.Models.TiqueteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cantidad");

                    b.Property<int>("Id_cliente");

                    b.Property<int>("Total");

                    b.Property<int>("id_ruta");

                    b.HasKey("Id");

                    b.HasIndex("Id_cliente");

                    b.HasIndex("id_ruta");

                    b.ToTable("TIQUETEITEM");
                });

            modelBuilder.Entity("PrParcial.Models.TiqueteItem", b =>
                {
                    b.HasOne("PrParcial.Models.ClienteItem", "ClienteItem")
                        .WithMany("TiqueteItems")
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrParcial.Models.RutaItem", "RutaItem")
                        .WithMany("TiqueteItems")
                        .HasForeignKey("id_ruta")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
